M48
; DRILL file {KiCad (6.0.9)} date Thu Dec  1 15:50:01 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-01T15:50:01+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.9343Y-0.7161
X0.9343Y-3.1461
X3.7543Y-0.7161
X3.7543Y-3.1461
T0
M30
